#Ce fichier contiens la config de base du serveur---
installation: false
licence: free-craftmywebsite.fr
General:
    url: 
    name: 
    theme: default
    themeOption: bootstrap
    description:
    keywords:
    bgType: 0
    permsPlugin: groupManager
    permsWorld: world
    ipTexte: 
    ip: 
    port: 
    statut: 2
    moneyName: "Jeton"
    createur: 
        nom: Cr√©ateur
        effets: style16
        couleur: '#ffffff'
        bg: '#b83d3d'
    joueur: Joueur
DataBase:
    dbAdress: 
    dbName: 
    dbUser: 
    dbPassword: 
    dbPort: 
Payement:
    paypal: true
    dedipass: false
    paysafecard: false
    currency: EUR
    public_key: ""
    private_key: ""
    paypalEmail: 
vote:
    maxDisplay: 10
color:
    panel:
        main: '#ff8040'
        hover: '#c16100'
        focus: '#ffbc9b'
